#inspiration: https://gist.github.com/rishitells/3c4536131819cff4eba2c8ab5bbb4570
# package.json jest path discovered in https://stackoverflow.com/questions/60671752/deploying-via-google-cloud-build-trigger-sh-1-jest-permission-denied
image: node:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - . build.sh
  only:
    - main
    - dev
  cache:
    paths:
      - server/node_modules/
      - client/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - server/node_modules/
      - client/node_modules/

test:
  stage: test
  only:
    - main
    - dev
  dependencies:
    - build
  script:
    - npm run test --prefix server

azure:
  stage: deploy
  only:
    - dev
  script:
    - . deploy.sh
